// SPDX-License-Identifier: MIT OR Apache-2.0
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Where to look for the other side of an edge that is not recorded.
///
/// A macro needs two: the definition that hides the call, and the invocation
/// that supplied the name. A hardware gate needs the table entry that installs
/// the handler as well as the assembly stub. One location per row would force
/// every consumer to re-derive the rest, and each would derive it differently.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EdgeLocation {
    /// What this location is: `definition`, `invocation`, `declaration`,
    /// `installation`, `stub`.
    pub role: String,
    pub file_path: String,
    pub line: u32,
}

/// An edge the index cannot record, with what it takes to find the other side.
///
/// `callers bdi_debug_stats_show` answering "No functions call it" ends a
/// search. Saying instead that the name is handed to `single_open` inside a
/// body generated by `DEFINE_SHOW_ATTRIBUTE`, at these two places, lets it
/// continue. The three parts are all required: what is known, the mechanism
/// blocking the edge, and somewhere to look. A reason code without a location
/// is a shrug.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UnresolvedEdge {
    /// The end of the edge that is known.
    pub name: String,
    /// `in` where the caller is unknown, `out` where the callee is.
    pub direction: String,
    /// The mechanism, namespaced by language: `c:macro_parameter_call`,
    /// `c:gate_idt`, `c:planted_return_address`, `c:assembly`. An open string
    /// and not an enum: a vocabulary shared by C macros, Rust trait objects
    /// and Python attribute lookup would describe none of them.
    pub kind: String,
    /// What the source writes where the name would be: a macro parameter, a
    /// pasted fragment, an attribute string. Outside C this is often the only
    /// thing naming the other side.
    pub evidence: String,
    /// Everywhere worth looking, each with its role. The first is the most
    /// actionable and is duplicated into the indexed columns.
    pub locations: Vec<EdgeLocation>,
    pub file_path: String,
    pub git_file_hash: String,
    pub line: u32,
}

/// One definition of a name, with what that definition calls.
///
/// A name in C is not one thing. `pr_warn` has nine definitions in the Linux
/// tree; a caller in `mm/` reaches the one in `include/linux/printk.h` and a
/// caller under `tools/` reaches a different one. Answering with a single
/// definition's callees means answering for a caller nobody asked about, so the
/// definitions are kept apart and the file each came from is reported with it.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalleeDefinition {
    pub file_path: String,
    pub line_start: u32,
    pub line_end: u32,
    pub callees: Vec<String>,
    /// False where the row is a prototype. A prototype answers nothing about
    /// what a name calls, and nearly every exported function has one, so
    /// counting it as a second definition would call almost every name
    /// ambiguous. A definition that calls nothing is not a prototype: it is a
    /// second answer, and a different one.
    pub is_definition: bool,
}

/// Where one definition of a name was read.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DefinitionSite {
    pub file_path: String,
    pub line_start: u32,
}

/// The definition a command that must give one answer is about, beside the
/// definitions of the same name it set aside.
///
/// A command that walks a chain or lists callers needs one starting point, so
/// it cannot report every definition the way a callee query does. Carrying the
/// others with the choice lets it name them, which is the difference between
/// picking one and hiding that there was a choice.
#[derive(Debug, Clone)]
pub struct ChosenDefinition {
    pub function: FunctionInfo,
    pub others: Vec<DefinitionSite>,
}

impl ChosenDefinition {
    /// The only definition of the name, so there was no choice to report.
    pub fn only(function: FunctionInfo) -> Self {
        ChosenDefinition {
            function,
            others: Vec::new(),
        }
    }

    /// What to tell a reader before an answer about one of several definitions.
    ///
    /// `None` where the name has one definition: a note on every answer would
    /// be noise, and noise is skipped rather than read.
    pub fn ambiguity_note(&self) -> Option<String> {
        if self.others.is_empty() {
            return None;
        }
        let mut sites: Vec<String> = self
            .others
            .iter()
            .map(|site| format!("{}:{}", site.file_path, site.line_start))
            .collect();
        sites.sort();
        // A name with a hundred definitions would otherwise print a hundred
        // paths, and a note too long to read is not read. The count is the
        // part that cannot be cut: it says an answer was chosen.
        const SHOWN: usize = 8;
        let listed = if sites.len() > SHOWN {
            format!(
                "{}, and {} more ('func {}' lists them all)",
                sites[..SHOWN].join(", "),
                sites.len() - SHOWN,
                self.function.name
            )
        } else {
            sites.join(", ")
        };
        Some(format!(
            "'{}' is defined {} times in this revision. This answer is about \
             {}:{}; the others are {}. Which one a call site reaches depends on \
             the file it is written in and on the configuration the tree is \
             built with, and neither is recorded here.",
            self.function.name,
            self.others.len() + 1,
            self.function.file_path,
            self.function.line_start,
            listed
        ))
    }
}

/// Whether a path holds a program other than the one an audit is about.
///
/// A source tree can build more than one program. Linux builds host tools from
/// every directory named `tools` -- the top-level one and `arch/x86/tools`,
/// `arch/arm64/tools`, `drivers/comedi/drivers/ni_routing/tools` and nine more
/// -- example code from `samples`, and prose from `Documentation`. Those
/// programs define names the kernel also defines: of nine definitions of
/// `pr_warn`, eight are outside the kernel image.
///
/// A path component, not a prefix: the definition that made this necessary is
/// `arch/x86/tools/insn_decoder_test.c`, which no prefix of `tools/` matches.
/// Every directory named `tools` in that tree holds a host program, so the
/// component is the signal.
///
/// This orders a choice between definitions. It never drops one: a name defined
/// only under `tools` still answers, and the choice is reported either way, so
/// a tie-break that goes the wrong way is visible rather than silent.
///
/// `scripts` and `usr` are deliberately absent, though they read as though they
/// belong: both hold code that ends up in the built image. `scripts/module-common.c`
/// is compiled into every `.ko` (`scripts/Makefile.modfinal:28`) and
/// `usr/initramfs_data.S` is linked in, so the directory name does not imply
/// another program there the way it does for `tools`.
pub fn path_is_other_program(file_path: &str) -> bool {
    const OTHER_PROGRAMS: [&str; 3] = ["tools", "samples", "Documentation"];
    file_path
        .split('/')
        .any(|component| OTHER_PROGRAMS.contains(&component))
}

/// The language a path's extension names, for grouping definitions of one name.
///
/// Coarse on purpose: the question is only whether two definitions of a name
/// are written in the same language, not which dialect. An unrecognised
/// extension is its own group rather than being folded into one of these, so a
/// file type nobody has thought about does not silently join C.
pub fn path_language(file_path: &str) -> &str {
    match file_path.rsplit_once('.') {
        Some((_, "c" | "h" | "cc" | "cpp" | "cxx" | "hh" | "hpp" | "inc")) => "c",
        Some((_, extension)) => extension,
        None => "",
    }
}

/// Whether stored text declares a function without defining it.
///
/// The row's own text is the only thing that separates the two: a prototype
/// stores `extern ssize_t vfs_read(struct file *, ...);` and a definition
/// stores its braces. Comments are removed first, since a brace inside one is
/// prose, and a macro is a definition however it is written.
pub fn text_is_prototype(body: &str) -> bool {
    let mut code = String::with_capacity(body.len());
    let bytes = body.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'/' && bytes.get(i + 1) == Some(&b'*') {
            i += 2;
            while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                i += 1;
            }
            i += 2;
            continue;
        }
        if bytes[i] == b'/' && bytes.get(i + 1) == Some(&b'/') {
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        code.push(bytes[i] as char);
        i += 1;
    }
    let code = code.trim();
    !code.starts_with('#') && !code.contains('{') && code.ends_with(';')
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionInfo {
    pub name: String,
    pub file_path: String,
    pub git_file_hash: String, // Git hash of the file content as hex string
    pub line_start: u32,
    pub line_end: u32,
    pub return_type: String,
    pub parameters: Vec<ParameterInfo>,
    pub body: String,
    #[serde(default)]
    pub calls: Option<Vec<String>>, // Function names called by this function
    #[serde(default)]
    pub types: Option<Vec<String>>, // Type names used by this function
}

/// Parameters for creating FunctionInfo from a macro
#[derive(Debug, Clone)]
pub struct MacroParams {
    pub name: String,
    pub file_path: String,
    pub git_file_hash: String,
    pub line_start: u32,
    pub parameters: Vec<String>,
    pub definition: String,
    pub calls: Option<Vec<String>>,
    pub types: Option<Vec<String>>,
}

impl FunctionInfo {
    /// Create a FunctionInfo for a function-like macro
    /// Macros are treated as functions with empty return types and untyped parameters
    pub fn from_macro(params: MacroParams) -> Self {
        let MacroParams {
            name,
            file_path,
            git_file_hash,
            line_start,
            parameters,
            definition,
            calls,
            types,
        } = params;
        // Convert simple parameter names to ParameterInfo structs
        let params = parameters
            .into_iter()
            .map(|p| ParameterInfo {
                name: p,
                type_name: String::new(), // Macros don't have typed parameters
                type_file_path: None,
                type_git_file_hash: None,
            })
            .collect();

        Self {
            name,
            file_path,
            git_file_hash,
            line_start,
            line_end: line_start,       // Macros are single-line in our model
            return_type: String::new(), // Macros don't have return types
            parameters: params,
            body: definition,
            calls,
            types,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParameterInfo {
    pub name: String,      // Parameter name (e.g., "buffer")
    pub type_name: String, // Type name (e.g., "struct buffer_head")
    #[serde(default)]
    pub type_file_path: Option<String>, // File where type is defined
    #[serde(default)]
    pub type_git_file_hash: Option<String>, // Hash of file containing type definition
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeInfo {
    pub name: String,
    pub file_path: String,
    pub git_file_hash: String, // Git hash of the file content as hex string
    pub line_start: u32,
    pub kind: String,
    pub size: Option<u64>,
    pub members: Vec<FieldInfo>,
    pub definition: String, // Added to store raw type definition with comments
    #[serde(default)]
    pub types: Option<Vec<String>>, // Type names referenced by this type
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FieldInfo {
    pub name: String,
    pub type_name: String,
    pub offset: Option<u64>,
}

/// A call that dispatches through a value rather than naming a function:
/// `ops->read(...)`, `(*fp)(...)`, a callback handed to another function.
///
/// The candidates are not known when the site is recorded. Resolution joins
/// `(receiver_type, member)` against the functions installed in that slot, so
/// what is stored here is only what the containing file itself proves.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DispatchSite {
    /// Function containing the call site, empty when there is none: Python
    /// module level and class bodies, C++ and Rust static initializers. The
    /// empty string is the stored form; the column is not nullable.
    pub caller_name: String,
    pub file_path: String,
    pub git_file_hash: String,
    /// Byte offset of the site within the file: unique per site, and stable
    /// across a reindex of unchanged content.
    pub byte_start: u64,
    pub line: u32,
    /// Member dispatched through, empty when the call goes through a plain
    /// pointer value with no member involved.
    pub member: String,
    /// Receiver text as written, for display and for later type resolution.
    pub receiver_expr: Option<String>,
    /// Receiver type when the containing file proves it.
    pub receiver_type: Option<String>,
    /// For a receiver that is itself a field access, `inode->i_fop->read()`,
    /// the type of the base and the field read from it: `inode` and `i_fop`.
    /// The receiver's own type is the type of that field, which lives in
    /// whichever file declares the struct, so resolution finishes the job
    /// against the types table. Both are set together or not at all.
    pub receiver_base_type: Option<String>,
    pub receiver_field: Option<String>,
    pub kind: DispatchKind,
    /// A target the site itself names, such as a local pointer's initializer.
    pub target: Option<String>,
}

/// A dispatch site with the functions it can reach, which is what a call
/// chain needs to continue through it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedDispatch {
    pub receiver_expr: String,
    pub container_type: String,
    pub member: String,
    pub file_path: String,
    pub line: u32,
    /// Everything installed in that member of that type, as written. A
    /// target that is not a function in the tree drops out when the caller
    /// looks it up.
    pub targets: Vec<String>,
}

/// The member recorded for a call through, or an installation into, an
/// element of an array of function pointers.
///
/// A table has no members to name, so both sides of the join use this in
/// place of one and the container is the array itself. No struct declares a
/// member of this name, so a table cannot collide with a type.
pub const ARRAY_ELEMENT_MEMBER: &str = "[]";

/// The member recorded for a call through, or an installation into, a
/// static-call key.
///
/// A key holds one function, patched into the call site at run time, so there
/// is no member and no index — the key is the whole slot. As with a table,
/// both sides of the join use this in place of a member name.
pub const STATIC_CALL_MEMBER: &str = "()";

/// How a dispatch site was written. Stored, so values are append-only.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DispatchKind {
    /// `receiver->member(...)`
    MemberArrow,
    /// `receiver.member(...)`
    MemberDot,
    /// `(*fp)(...)`
    PointerDeref,
    /// `fp(...)` where `fp` is a function pointer declared in this function
    PointerLocal,
    /// `fp(...)` where `fp` is a function-pointer parameter
    PointerParam,
    /// A candidate the source itself names, as the kernel's INDIRECT_CALL_n
    /// macros do to help the branch predictor.
    MacroDeclared,
    /// `table[i](...)`: a call through an element of an array of function
    /// pointers. The table is the container; a runtime index leaves every
    /// element it holds a candidate.
    ArrayElement,
    /// `static_call(key)(...)`: a direct call patched at run time to whatever
    /// was installed in the key.
    StaticCall,
}

impl DispatchKind {
    pub fn as_str(self) -> &'static str {
        match self {
            DispatchKind::MemberArrow => "member_arrow",
            DispatchKind::MemberDot => "member_dot",
            DispatchKind::PointerDeref => "pointer_deref",
            DispatchKind::PointerLocal => "pointer_local",
            DispatchKind::PointerParam => "pointer_param",
            DispatchKind::MacroDeclared => "macro_declared",
            DispatchKind::ArrayElement => "array_element",
            DispatchKind::StaticCall => "static_call",
        }
    }

    /// Parse a stored `kind`. An unknown value is an error for the caller
    /// rather than a silent default: a newer writer must not read as a
    /// member call.
    pub fn from_column_value(text: &str) -> Option<Self> {
        match text {
            "member_arrow" => Some(DispatchKind::MemberArrow),
            "member_dot" => Some(DispatchKind::MemberDot),
            "pointer_deref" => Some(DispatchKind::PointerDeref),
            "pointer_local" => Some(DispatchKind::PointerLocal),
            "pointer_param" => Some(DispatchKind::PointerParam),
            "macro_declared" => Some(DispatchKind::MacroDeclared),
            "array_element" => Some(DispatchKind::ArrayElement),
            "static_call" => Some(DispatchKind::StaticCall),
            _ => None,
        }
    }
}

/// A function installed in a struct member: the other half of a dispatch
/// site. `.read = my_read` in a `struct file_operations` initializer says
/// that a call through `file_operations::read` can reach `my_read`.
///
/// The target is recorded as written. Whether it names a function is not
/// knowable while parsing one file, and does not need to be: resolution
/// joins the target against the functions table, and an initializer holding
/// a constant simply never joins.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Registration {
    /// Struct or typedef whose member is being initialised. Empty when the
    /// file did not state it and `container_base_type` did: an assignment
    /// through a field, `s->s_shrink->scan_objects = f`, knows what `s` is
    /// but not what `s_shrink` is declared as. Resolution fills it in.
    pub container_type: String,
    pub member: String,
    /// Identifier the member is initialised with.
    pub target: String,
    pub file_path: String,
    pub git_file_hash: String,
    pub byte_start: u64,
    pub line: u32,
    /// Function containing the initializer, empty at file scope.
    pub enclosing_function: String,
    pub kind: RegistrationKind,
    /// For `base->field->member = f`, the type of the base and the path of
    /// fields read from it. Set together, and only when the container type
    /// could not be read from the file directly.
    pub container_base_type: Option<String>,
    pub container_field: Option<String>,
}

/// A file-scope variable of aggregate type.
///
/// `extern struct machdep_calls ppc_md;` sits in a header, so a file calling
/// `ppc_md.memory_block_size()` never declares it and cannot type the
/// receiver. Recorded here, the type is available where the answer is given.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GlobalVariable {
    pub name: String,
    /// Aggregate the declaration names, without `struct` or qualifiers.
    pub type_name: String,
    pub file_path: String,
    pub git_file_hash: String,
    pub line: u32,
}

/// What the call a function was handed to does with it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Handover {
    /// Written into a struct member, reachable from there by dispatch.
    StoredIn {
        /// Calls walked to reach it, wrappers included.
        path: Vec<String>,
        container_type: String,
        member: String,
    },
    /// Called by the callee, so the handover is itself a call edge.
    Invoked { path: Vec<String> },
}

impl Handover {
    /// Whether the call happens after the handover returns.
    ///
    /// Storing a function in a member defers it by construction: whoever
    /// dispatches through that member runs it, at a time the installing
    /// caller does not choose. `INIT_WORK` and `call_rcu` store; `kref_put`
    /// calls what it is given before it returns.
    ///
    /// Two chains that differ only in this are the same graph to a reader and
    /// different worlds to anyone reasoning about a race, so the answer says
    /// which one it is rather than leaving it to be inferred from the
    /// registrar's name.
    pub fn fires_later(&self) -> bool {
        matches!(self, Handover::StoredIn { .. })
    }
}

/// A function named as an argument of a call: `request_irq(irq, handler, ...)`.
///
/// Whether the callee does anything with it is a separate question, answered
/// where the callee's own body is known. This records only what the file
/// proves: at this call, this argument names this identifier.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArgumentFunction {
    /// Identifier named by the argument.
    pub target: String,
    /// Name being called. A macro at this point is indistinguishable from a
    /// function, and the two are told apart against the functions table.
    pub callee: String,
    /// Zero-based position among the arguments.
    pub argument_index: u32,
    /// `&handler` rather than `handler`. Both install a function; the address
    /// form also appears where the argument is an object, so it is kept.
    pub taken_address: bool,
    /// The object the function is being attached to, where another argument
    /// names one: `call_rcu(&inode->i_rcu, i_callback)` attaches the callback
    /// to an inode through `i_rcu`. Set together, and only where the file
    /// declares the base's type.
    pub subject_type: Option<String>,
    pub subject_member: Option<String>,
    pub file_path: String,
    pub git_file_hash: String,
    pub byte_start: u64,
    pub line: u32,
    /// Function containing the call, empty at file scope.
    pub enclosing_function: String,
}

/// How a function came to be installed. Stored, so values are append-only.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RegistrationKind {
    /// `.member = target` inside an initializer
    DesignatedInit,
    /// `x->member = target;` or `x.member = target;`
    Assignment,
}

impl RegistrationKind {
    pub fn as_str(self) -> &'static str {
        match self {
            RegistrationKind::DesignatedInit => "designated_init",
            RegistrationKind::Assignment => "assignment",
        }
    }

    pub fn from_column_value(text: &str) -> Option<Self> {
        match text {
            "designated_init" => Some(RegistrationKind::DesignatedInit),
            "assignment" => Some(RegistrationKind::Assignment),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypedefInfo {
    pub name: String,
    pub file_path: String,
    pub git_file_hash: String, // Git hash of the file content as hex string
    pub line_start: u32,
    pub underlying_type: String,
    pub definition: String,
}

/// Git commit metadata with changed symbols
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitCommitInfo {
    pub git_sha: String,                    // The commit SHA
    pub parent_sha: Vec<String>,            // Parent commit SHAs (multiple for merges)
    pub author: String,                     // Author name and email
    pub subject: String,                    // Single line commit title
    pub message: String,                    // Full commit message
    pub tags: HashMap<String, Vec<String>>, // Tags from commit message (Signed-off-by:, etc.)
    pub diff: String,                       // Full unified diff
    pub symbols: Vec<String>,               // Changed symbols (filename:symbol() format)
    pub files: Vec<String>,                 // List of files changed by this commit
}

/// Lore email information extracted from a commit's 'm' file
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoreEmailInfo {
    pub git_commit_sha: String,      // Git commit SHA containing this email
    pub from: String,                // From header in the email
    pub date: String,                // Date field (RFC 2822 format)
    pub date_timestamp: i64,         // Unix timestamp for efficient date filtering
    pub message_id: String,          // Message-ID header
    pub in_reply_to: Option<String>, // In-Reply-To header (nullable)
    pub subject: String,             // Subject line
    pub references: Option<String>,  // Full list of References headers (nullable)
    pub recipients: String,          // Full list of To/CC recipients
    pub body: String,                // Email body (everything after first blank line)
    pub symbols: Vec<String>,        // List of symbols referenced in the email (empty for now)
}

/// Global type registry for cross-file type resolution
#[derive(Debug, Clone)]
pub struct GlobalTypeRegistry {
    /// Map from type name to type information
    pub types: HashMap<String, TypeInfo>,
    /// Map from typedef name to typedef information
    pub typedefs: HashMap<String, TypedefInfo>,
}

impl Default for GlobalTypeRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl GlobalTypeRegistry {
    pub fn new() -> Self {
        Self {
            types: HashMap::new(),
            typedefs: HashMap::new(),
        }
    }

    /// Register types from analysis results
    pub fn register_types(&mut self, types: Vec<TypeInfo>, typedefs: Vec<TypedefInfo>) {
        for type_info in types {
            self.types.insert(type_info.name.clone(), type_info);
        }
        for typedef_info in typedefs {
            self.typedefs
                .insert(typedef_info.name.clone(), typedef_info);
        }
    }

    /// Look up type information by name, checking both types and typedefs
    pub fn lookup_type(&self, type_name: &str) -> Option<(String, String)> {
        // Remove common type prefixes and suffixes for lookup
        let cleaned_name = self.clean_type_name(type_name);

        // First check direct types
        if let Some(type_info) = self.types.get(&cleaned_name) {
            return Some((type_info.file_path.clone(), type_info.git_file_hash.clone()));
        }

        // Then check typedefs
        if let Some(typedef_info) = self.typedefs.get(&cleaned_name) {
            return Some((
                typedef_info.file_path.clone(),
                typedef_info.git_file_hash.clone(),
            ));
        }

        None
    }

    /// Clean type name by removing common C/C++ type decorations
    fn clean_type_name(&self, type_name: &str) -> String {
        let cleaned = type_name
            .trim()
            .replace("const ", "")
            .replace("volatile ", "")
            .replace("static ", "")
            .replace("extern ", "")
            .replace("inline ", "")
            .replace(" *", "")
            .replace("*", "")
            .replace(" &", "")
            .replace("&", "")
            .trim()
            .to_string();

        // Handle array syntax like "char[256]" or "unsigned long [ 2 ]"
        if let Some(bracket_pos) = cleaned.find('[') {
            cleaned[..bracket_pos].trim().to_string()
        } else {
            cleaned
        }
    }
}

/// Represents a file from a git commit stored in a temporary file
#[derive(Debug, Clone)]
pub struct GitFileEntry {
    pub relative_path: std::path::PathBuf,
    pub blob_id: String,
    pub temp_file_path: std::path::PathBuf,
}

impl GitFileEntry {
    /// Manually clean up the temporary file
    pub fn cleanup(&self) -> std::io::Result<()> {
        if self.temp_file_path.exists() {
            std::fs::remove_file(&self.temp_file_path)?;
        }
        Ok(())
    }
}

impl Drop for GitFileEntry {
    fn drop(&mut self) {
        // Best effort cleanup - don't panic on errors
        if self.temp_file_path.exists() {
            if let Err(e) = std::fs::remove_file(&self.temp_file_path) {
                tracing::warn!(
                    "Failed to cleanup temp file {}: {}",
                    self.temp_file_path.display(),
                    e
                );
            }
        }
    }
}

/// Lightweight reference to a git file for on-demand loading
#[derive(Debug, Clone)]
pub struct GitFileManifestEntry {
    pub relative_path: std::path::PathBuf,
    pub object_id: gix::ObjectId,
}
